# GET http://192.168.111.231:8080/settings

POST  http://192.168.111.231:8080/settings
content-type: application/json
User: 123456

{
  "settings": [
    {
    "key": "homeTopBg",
    "value": 1,
    "desc": "首页背景图片"
  },
  {
    "key": "Portra",
    "value": {
      "name": "人像布控",
      "enName": "Portra",
      "icon": 1
    },
    "desc": "首页人像布控模块"
  },
  {
    "key": "Alarm",
    "value": {
      "name": "告警",
      "enName": "Alarm",
      "icon": 1
    },
    "desc": "首页告警模块"
  }
  ]
},

